# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  vehicle.profiler.api.collector:
    class: App\DataCollector\ApiCollector
    arguments:
      - '@vehicle.api.service'
      - '@jms_serializer.serializer'
    tags:
      - { name: data_collector, template: 'Profiler/api.html.twig', id: api }

  vehicle.profiler.git.collector:
    class: App\DataCollector\GitCollector
    arguments:
      - '@vehicle.api.service'
      - '@jms_serializer.serializer'
    tags:
      - { name: data_collector, template: 'Profiler/git.html.twig', id: git }

  vehicle.profiler.api.log.collector:
    class: App\DataCollector\ApiLogCollector
    arguments:
      - '@kernel'
    tags:
      - { name: data_collector, template: 'Profiler/api-logs.html.twig', id: api-log }

  vehicle.request.listener:
    class: App\Listener\RequestListener
    arguments:
      - '@router'
      - '@vehicle.api.service'
    tags:
      - { event: kernel.request, name: kernel.event_listener, method: listen, priority: 0 }

  vehicle.api.service:
    class: App\Services\ApiService
    arguments:
      - '@vehicle.api.adapter'
      - '@vehicle.authorization.service'

  vehicle.api.log.service:
    class: App\Services\ApiLogService
    arguments:
      - '@monolog.logger.api'

  vehicle.api.log.listener:
    class: App\Listener\ApiLogListener
    arguments:
      - '@vehicle.api.log.service'

  vehicle.api.adapter:
    class: App\Services\ApiAdapter
    arguments:
      - "@jms_serializer.serializer"
      - "@event_dispatcher"

  vehicle.menu.factory:
    class: App\Menu\Menu
    arguments:
      - '@knp_menu.factory'
    tags:
      - { name: knp_menu.menu_builder, method: createSidebarMenu, alias: sidebar }

  vehicle.authorization.service:
    class: App\Services\AuthorizationService

  vehicle.user.service:
    class: App\Services\UserService
    arguments:
      - "@vehicle.api.adapter"